### STAGE 1
FROM maven:3.6.3-jdk-14 as build
WORKDIR /workspace

COPY ./pom.xml /workspace
COPY ./web-externalApp/pom.xml /workspace/web-externalApp/pom.xml
COPY ./web-internalApp/pom.xml /workspace/web-internalApp/pom.xml
COPY ./components/pom.xml /workspace/components/pom.xml

COPY ./web-externalApp/src /workspace/web-externalApp/src
COPY ./web-internalApp/src /workspace/web-internalApp/src
COPY ./components/src /workspace/components/src

#COPY ./ /workspace
RUN mvn -B -f pom.xml clean package -DskipTests

### STAGE 2
FROM openjdk:14-jdk-slim
EXPOSE 8081
#ENV MYSQL_HOST 192.168.2.11
COPY --from=build /workspace/web-internalApp/target/*.jar app.jar
#ENTRYPOINT ["java","-jar","app.jar"]